### ISSUE TITLE
Send email as plain text? (HTML will be stripped) not working

### ISSUE THREAD

**Issue by ghost** [lekoala/silverstripe-mailgun#9]
Hi there.

There seems to be an issue when selecting the option 'Send email as plain text? (HTML will be stripped)' inside Email Content under a Recipient.

The inline_styles function inside EmailUtils.php receives an $html parameter, but it is always null for me.

[2022-02-16 08:36:38] error-log.ERROR: InvalidArgumentException: The provided HTML must be a string. in /Users/pod9/Sites/citycare.co.nz/vendor/pelago/emogrifier/src/Emogrifier/HtmlProcessor/AbstractHtmlProcessor.php:64 Stack trace: #0 /Users/pod9/Sites/citycare.co.nz/vendor/lekoala/silverstripe-mailgun/src/EmailUtils.php(25): Pelago\Emogrifier\HtmlProcessor\AbstractHtmlProcessor::fromHtml(NULL) #1 /Users/pod9/Sites/citycare.co.nz/vendor/lekoala/silverstripe-mailgun/src/MailgunSwiftTransport.php(502): LeKoala\Mailgun\EmailUtils::inline_styles(NULL) #2 /Users/pod9/Sites/citycare.co.nz/vendor/lekoala/silverstripe-mailgun/src/MailgunSwiftTransport.php(120): LeKoala\Mailgun\MailgunSwiftTransport->buildMessage(Object(Swift_Message)) #3 /Users/pod9/Sites/citycare.co.nz/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): LeKoala\Mailgun\MailgunSwiftTransport->send(Object(Swift_Message), Array) #4 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Email/SwiftMailer.php(55): Swift_Mailer->send(Object(Swift_Message), Array) #5 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Email/SwiftMailer.php(42): SilverStripe\Control\Email\SwiftMailer->sendSwift(Object(Swift_Message), Array) #6 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Email/Email.php(817): SilverStripe\Control\Email\SwiftMailer->send(Object(SilverStripe\Control\Email\Email)) #7 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/userforms/code/Control/UserDefinedFormController.php(435): SilverStripe\Control\Email\Email->sendPlain() #8 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Forms/FormRequestHandler.php(530): SilverStripe\UserForms\Control\UserDefinedFormController->process(Array, Object(SilverStripe\UserForms\Form\UserForm), Object(SilverStripe\Control\HTTPRequest), Object(SilverStripe\Forms\FormRequestHandler)) #9 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Forms/FormRequestHandler.php(231): SilverStripe\Forms\FormRequestHandler->invokeFormHandler(Object(SilverStripe\UserForms\Control\UserDefinedFormController), 'process', Object(SilverStripe\Control\HTTPRequest), Array) #10 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/RequestHandler.php(323): SilverStripe\Forms\FormRequestHandler->httpSubmission(Object(SilverStripe\Control\HTTPRequest)) #11 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/RequestHandler.php(202): SilverStripe\Control\RequestHandler->handleAction(Object(SilverStripe\Control\HTTPRequest), 'httpSubmission') #12 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/RequestHandler.php(226): SilverStripe\Control\RequestHandler->handleRequest(Object(SilverStripe\Control\HTTPRequest)) #13 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Controller.php(212): SilverStripe\Control\RequestHandler->handleRequest(Object(SilverStripe\Control\HTTPRequest)) #14 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/cms/code/Controllers/ContentController.php(251): SilverStripe\Control\Controller->handleRequest(Object(SilverStripe\Control\HTTPRequest)) #15 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/cms/code/Controllers/ModelAsController.php(101): SilverStripe\CMS\Controllers\ContentController->handleRequest(Object(SilverStripe\Control\HTTPRequest)) #16 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Director.php(360): SilverStripe\CMS\Controllers\ModelAsController->handleRequest(Object(SilverStripe\Control\HTTPRequest)) #17 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/versioned/src/VersionedHTTPMiddleware.php(41): SilverStripe\Control\Director->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) #18 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Versioned\VersionedHTTPMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #19 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/session-manager/src/Middleware/LoginSessionMiddleware.php(53): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #20 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\SessionManager\Middleware\LoginSessionMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #21 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/ExecMetricMiddleware.php(20): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #22 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\ExecMetricMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #23 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/ConfirmationMiddleware.php(254): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #24 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\ConfirmationMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #25 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/ConfirmationMiddleware.php(254): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #26 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\ConfirmationMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #27 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Security/PasswordExpirationMiddleware.php(84): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #28 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\PasswordExpirationMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #29 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Security/BasicAuthMiddleware.php(68): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #30 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\BasicAuthMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #31 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Security/AuthenticationMiddleware.php(61): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #32 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Security\AuthenticationMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #33 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/CanonicalURLMiddleware.php(190): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #34 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\CanonicalURLMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #35 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPCacheControlMiddleware.php(42): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #36 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #37 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/ChangeDetectionMiddleware.php(28): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #38 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\ChangeDetectionMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #39 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/FlushMiddleware.php(27): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #40 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\FlushMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #41 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/RequestProcessor.php(66): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #42 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\RequestProcessor->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #43 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/SessionMiddleware.php(20): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #44 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\SessionMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #45 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/AllowedHostsMiddleware.php(60): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #46 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\AllowedHostsMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #47 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/TrustedProxyMiddleware.php(176): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #48 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(62): SilverStripe\Control\Middleware\TrustedProxyMiddleware->process(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #49 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\Director->SilverStripe\Control\Middleware\{closure}(Object(SilverStripe\Control\HTTPRequest)) #50 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Director.php(369): SilverStripe\Control\Director->callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #51 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(117): SilverStripe\Control\Director->handleRequest(Object(SilverStripe\Control\HTTPRequest)) #52 [internal function]: SilverStripe\Control\HTTPApplication::SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) #53 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(136): call_user_func(Object(Closure), Object(SilverStripe\Control\HTTPRequest)) #54 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/Middleware/HTTPMiddlewareAware.php(65): SilverStripe\Control\HTTPApplication->SilverStripe\Control\{closure}(Object(SilverStripe\Control\HTTPRequest)) #55 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(137): SilverStripe\Control\HTTPApplication->callMiddleware(Object(SilverStripe\Control\HTTPRequest), Object(Closure)) #56 /Users/pod9/Sites/citycare.co.nz/vendor/silverstripe/framework/src/Control/HTTPApplication.php(116): SilverStripe\Control\HTTPApplication->execute(Object(SilverStripe\Control\HTTPRequest), Object(Closure), false) #57 /Users/pod9/Sites/citycare.co.nz/public/index.php(24): SilverStripe\Control\HTTPApplication->handle(Object(SilverStripe\Control\HTTPRequest)) #58 {main} [] []

**Comment by lekoala** [comment]
yes that makes sense, i've just updated master to avoid inlining if no html body exists. you can check? i'll tag a proper release if it works
